name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        use: actions/checkout@v2
      - name: Upload artifact
        use: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
